### ISSUE TITLE
[建议] 配置文件增加从其他源下载插件的选项（类似ghproxy.com这种）

### ISSUE THREAD

**Issue by OptiJava** [Ivan-1F/MCDReforgedPluginManager#5]
在服务器搞代理稍稍有些麻烦，而且代理不太稳定，相比来看好像从类似ghproxy.com的这种国内的github下载站安装/更新插件更好一点（

而且ghproxy使用起来很方便，稳定性也不用担心，只要把从github下载的地址放到 https://ghproxy.com/ 的后面就行了，比如：https://ghproxy.com/https://github.com/Ivan-1F/MCDReforgedPluginManager/releases/download/v1.3.3/MCDReforgedPluginManager-v1.3.3.mcdr

其他的大多数github国内下载站也是直接把github的网址放在后面就行，比如从 https://git.xfj0.cn/ 下载mpm：https://git.xfj0.cn/https://github.com/Ivan-1F/MCDReforgedPluginManager/releases/download/v1.3.3/MCDReforgedPluginManager-v1.3.3.mcdr

所以能不能加一下，万分感谢（

（我是萌新有说错的原谅一下

**Comment by Ivan-1F** [comment]
已于 [v2.0.0](https://github.com/Ivan-1F/MCDReforgedPluginManager/releases/tag/v2.0.0) 中添加
