### ISSUE TITLE
[建议] 插件库索引更新失败时能否保留旧的插件库索引

### ISSUE THREAD

**Issue by leiuary** [Ivan-1F/MCDReforgedPluginManager#8]
插件库索引因为网络原因大概率更新失败，此时能否保留旧的索引，或者增加手动更新的提示？
游戏内不太容易发现更新失败，这个时候因为没有索引，!!mpm list等命令也没有反馈
ps：默认的定时更新间隔2似乎会使后台刷屏

**Comment by Ivan-1F** [comment]
已发布 [v2.2.0](https://github.com/Ivan-1F/MCDReforgedPluginManager/releases/tag/v2.2.0)

**Comment by leiuary** [comment]
好耶！
