### ISSUE TITLE
"requests" should be included in "Requirements" in "README"

### ISSUE THREAD

**Issue by LingEmberMaple** [Ivan-1F/MCDReforgedPluginManager#9]

**Comment by Ivan-1F** [comment]
`requests` is already in https://github.com/Ivan-1F/MCDReforgedPluginManager/blob/master/requirements.txt

**Comment by LingEmberMaple** [comment]
Sorry, I didn't express myself clearly.  What I mean is that "requests" should be included in "Requirements" in "README".
